sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -e CI=true -t aenglisc/docker-react -f DockerFile.dev .

script:
  - docker run aenglisc/docker-react npm run test -- --coverage
