sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aenglisc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aenglisc/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-164344619799"
  bucket_path: "docker-react"
  on:
    branch: master
