sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aenglisc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aenglisc/docker-react npm run test -- --coverage
